version: "3"

services:
  postgresdb:
    image: postgres
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=devtravelpass
    ports:
      - "5432:5432"

#  redis:
#    image: redis
#    ports:
#      - "6379:6379"

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgresdb
    environment:
      - PROJECT_DIR=/usr/src/app
    entrypoint: /usr/src/bin/entrypoint.sh
    ports:
      - "8001:8001"

  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./media:/media
    depends_on:
      - web
    ports:
      - "80:80"
